### ISSUE TITLE
can't connect virtual instance to regular non virtual instances

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#723]
requires this [PR](https://github.com/gdsfactory/gdsfactory/pull/3972)

```
sample_all_angle = """
name: sample_all_angle

instances:
  s0:
    component: straight
    settings:
        length: 10
  b1:
    component: bend_euler_all_angle
    settings:
      radius: 10
      angle: 30
    virtual: True
  s1:
    component: straight
    settings:
      length: 10
    virtual: True
connections:
  s1,o1: b1,o2
  s0,o2: b1,o1
"""

if __name__ == "__main__":
    c = from_yaml(sample_all_angle)
```

--> 813 _place_and_connect(g, refs, net.connections, net.placements)
    814 c = _add_routes(c, refs, net.routes, routing_strategies)
    815 c = _add_ports(c, refs, net.ports)

File ~/c/pdks/gdsfactory/gdsfactory/read/from_yaml.py:981, in _place_and_connect(g, refs, connections, placements)
    979 if i2 not in refs:
    980     raise ValueError(f"{i2!r} not in {list(refs)}")
--> 981 refs[i1].connect(p1, other=refs[i2], other_port_name=p2)

File ~/c/kfactory/src/kfactory/instance.py:376, in ProtoTInstance.connect(self, port, other, other_port_name, mirror, allow_wid
th_mismatch, allow_layer_mismatch, allow_type_mismatch, use_mirror, use_angle)
    374     op = other.ports[other_port_name].to_itype()
    375 else:
--> 376     op = other.to_itype()
    377 if isinstance(port, ProtoPort):
    378     p = Port(base=port.base.transformed(self.dcplx_trans.inverted()))

AttributeError: 'VInstance' object has no attribute 'to_itype'
